# Generated by Django 3.1.3 on 2021-03-29 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolRestApi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schooluser',
            name='username',
        ),
        migrations.AlterField(
            model_name='schooluser',
            name='type',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Student', 'Student'), ('Teacher', 'Teacher')], max_length=20),
        ),
    ]
